apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clamav.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clamav.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-config.yaml") . | sha256sum }}
        checksum/commands: {{ include (print $.Template.BasePath "/configmap-commands.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clamav.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ quote . }}
      {{- end }}
      {{- if .Values.freshclam.enabled }}
      initContainers:
        - name: freshclam-init
          {{- with .Values.freshclam.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "clamav.freshclam.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_DIRECTORY
              value: {{ .Values.databaseDirectory }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          command: ["/sbin/tini", "--"]
          args: ["freshclam-init.sh"]
          volumeMounts:
            - name: config
              mountPath: /etc/clamav/freshclam.conf
              subPath: freshclam.conf
              readOnly: true
            - name: commands
              mountPath: /usr/local/bin/freshclam-init.sh
              subPath: freshclam-init.sh
              readOnly: true
            - mountPath: {{ .Values.databaseDirectory }}
              name: {{ include "clamav.pvcname" . }}
          {{- with .Values.freshclam.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: clamav
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "clamav.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          command: ["/sbin/tini", "--"]
          args: ["clamd", "--foreground"]
          ports:
            - name: clamavd
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/clamav/clamd.conf
              subPath: clamd.conf
              readOnly: true
            - name: commands
              mountPath: /usr/local/bin/clamdcheck.sh
              subPath: clamdcheck.sh
              readOnly: true
            {{ if gt (len .Values.yaraRules) 0 }}
            {{- range .Values.yaraRules }}
            - name: yararules
              mountPath: {{ printf "%s/yara_%s.yar" $.Values.databaseDirectory .name }}
              subPath: {{ .name }}
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if .Values.freshclam.enabled }}
            - mountPath: {{ .Values.databaseDirectory }}
              name: {{ include "clamav.pvcname" . }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.freshclam.enabled }}
        - name: freshclam
          {{- with .Values.freshclam.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "clamav.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          command: ["/sbin/tini", "--"]
          args: ["freshclam", "--foreground", "--stdout", "--daemon"]
          volumeMounts:
            - name: config
              mountPath: /etc/clamav/freshclam.conf
              subPath: freshclam.conf
              readOnly: true
            - mountPath: {{ .Values.databaseDirectory }}
              name: {{ include "clamav.pvcname" . }}
          {{- with .Values.freshclam.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "clamav.configname" . }}
            defaultMode: 0755
        - name: commands
          configMap:
            name: {{ template "clamav.commandsname" . }}
            defaultMode: 0777
        {{ if gt (len .Values.yaraRules) 0 }}
        - name: yararules
          configMap:
            name: {{ template "clamav.yararulesname" . }}
            defaultMode: 0755
        {{- end }}
        {{- if .Values.freshclam.enabled }}
        - name: {{ include "clamav.pvcname" . }}
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "clamav.pvcname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
